replicaCount: 1

image:
  repository: todo-api
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
   limits:
    cpu: 1000m
    memory: 1Gi
   requests:
    cpu: 1000m
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}
